; App configuration
[app]
name        = Welcome
author      = Your Name <you@example.com>
description = a cool new app
keywords    = web2py, python, framework
generator   = Web2py Web Framework
production  = false
toolbar     = false

; Host configuration
[host]
names = localhost:*, 127.0.0.1:*, *:*, *

; db configuration
[db]
uri       = sqlite://storage.sqlite
migrate   = true
pool_size = 10  

; smtp address and credentials
[smtp]
server = smtp.gmail.com:587
sender = you@gmail.com
login  = username:password
tls    = true
ssl    = true

[scheduler]
enabled   = false
heartbeat = 1


[google]
client_id =717323747733-3a0b2cboiq5l6gs90klfa860ofcciv3r.apps.googleusercontent.com
client_secret =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

[brave]
api_key =BSARlfzYGvIXs0rfqP3VkfSKa5dxjNG


[gemini]
api_key =AIzaSyBTXJPhqNK7u45x0R38xpBVDKHWzYadgdE